AppSchool/Models/Materias.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materias
    {
        public int ID_materias { get; set; }
        public int ID_curso { get; set; }
        public string Profesor { get; set; }
        public string Materia { get; set; }
        public string Horario { get; set; }
        public string Duracion { get; set; }
    
        public virtual Curso Curso { get; set; }
    }
}

AppSchool/Models/ViewModels/MateriaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AppSchool.Models.ViewModels
{
    public class MateriaViewModel
    {
        public int IdMaterias { get; set; }
        public int IdCurso { get; set; }
        public string Profesor { get; set; }
        public string Materia { get; set; }
        public string Horario { get; set; }
        public string Duracion { get; set; }
    }
}

AppSchool/Controllers/MateriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AppSchool.Models;
using AppSchool.Models.ViewModels;

namespace AppSchool.Controllers
{
    public class MateriaController : Controller
    {
        // GET: Curso
        public ActionResult Index()
        {
            List<ListMateriaViewModel> lst;
            using (SchoolAppEntities db = new SchoolAppEntities())
            {
                lst = (from d in db.Materias
                       select new ListMateriaViewModel
                       {
                           IdMaterias = d.ID_materias,
                           IdCurso = d.ID_curso,
                           Profesor = d.Profesor,
                           Materia = d.Materia,
                           Horario = d.Horario,
                           Duracion = d.Duracion
                       }).ToList();
            }
           

            return View(lst);
        }

        public ActionResult agregarMateria()
        {
            List<ListCursoViewModel> lst;
            using (SchoolAppEntities db = new SchoolAppEntities())
            {
                lst = (from d in db.Curso
                       select new ListCursoViewModel
                       {
                            IdCurso  = d.ID_curso,
                            Grado = d.Grado,
                            Seccion = d.Seccion
                       }).ToList();
            }
            List<SelectListItem> items = lst.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.Grado.ToString() + d.Seccion.ToString(),
                    Value = d.IdCurso.ToString(),
                    Selected = false
                };
            });

            ViewBag.listaID = items;
            return View();
        }

        [HttpPost]
        public ActionResult agregarMateria(MateriaViewModel model)
        {
            List<ListMateriaViewModel> lst;
            try
            {
                if (ModelState.IsValid)
                {
                    using (SchoolAppEntities db = new SchoolAppEntities())
                    {
                        var oTabla = new Materias();
                        oTabla.ID_curso = model.IdCurso;
                        oTabla.Profesor = model.Profesor;
                        oTabla.Materia = model.Materia;
                        oTabla.Horario = model.Horario;
                        oTabla.Duracion = model.Duracion;

                        db.Materias.Add(oTabla);
                        db.SaveChanges();

                    }
                    return Redirect("~/Materia/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult EditarMateria(int id)
        {
            MateriaViewModel model = new MateriaViewModel();
            using (SchoolAppEntities db = new SchoolAppEntities())
            {
                var oTabla = db.Materias.Find(id);
                model.IdCurso = oTabla.ID_curso;
                model.Profesor = oTabla.Profesor;
                model.Materia = oTabla.Materia;
                model.Horario = oTabla.Horario;
                model.Duracion = oTabla.Duracion;
                model.IdMaterias = oTabla.ID_materias;

            }
            return View(model);
        }

        [HttpPost]
        public ActionResult EditarMateria(MateriaViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (SchoolAppEntities db = new SchoolAppEntities())
                    {
                        var oTabla = db.Materias.Find(model.IdMaterias);
                        oTabla.ID_curso = model.IdCurso;
                        oTabla.Profesor = model.Profesor;
                        oTabla.Materia = model.Materia;
                        oTabla.Horario = model.Horario;
                        oTabla.Duracion = model.Duracion;

                        db.Entry(oTabla).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    return Redirect("~/Materia/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            using (SchoolAppEntities db = new SchoolAppEntities())
            {
                var oTabla = db.Materias.Find(id);
                db.Materias.Remove(oTabla);
                db.SaveChanges();
            }
            return Redirect("~/Materia/");
        }
    }
}

AppSchool/Views/Materia/EditarMateria.cshtml
@model AppSchool.Models.ViewModels.MateriaViewModel

@{
    ViewBag.Title = "Editar";
}



<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("EditarMateria", "Materia", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(d => d.IdMaterias)
            @Html.LabelFor(d => d.IdCurso)
            @Html.TextBoxFor(d => d.IdCurso, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Profesor)
            @Html.TextBoxFor(d => d.Profesor, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Materia)
            @Html.TextBoxFor(d => d.Materia, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Horario)
            @Html.TextBoxFor(d => d.Horario, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Duracion)
            @Html.TextBoxFor(d => d.Duracion, "", new { @class = "form-control" })
            <br />
        </div>
        <div style="margin-left:20px">
            <input value="Guardar" class="btn btn-primary" type="submit" />
        </div>
    </div>
}

AppSchool/Views/Materia/Index.cshtml
@model List<AppSchool.Models.ViewModels.ListMateriaViewModel>

    <div class="container">

        @{
            ViewBag.Title = "Materia";
        }

        <div class="page-header">
            <div class="text-center"><h1>Materia</h1></div>
        </div>

        <div class="row" style="text-align:right;padding:10px">
        <a href="~/Materia/agregarMateria" class="btn btn-primary">Nuevo</a>
        </div>

                <table class="table table-striped table-bordered text-center" >
                    <tr>
                        <th>ID</th>
                        <th>ID Curso</th>
                        <th>Profesor</th>
                        <th>Materia</th>
                        <th>Horario</th>
                        <th>Duracion</th>
                    </tr>

                    @foreach (var oElemento in Model)
                    {
                        <tr>
                            <td>@oElemento.IdMaterias</td>
                            <td>@oElemento.IdCurso</td>
                            <td>@oElemento.Profesor</td>
                            <td>@oElemento.Materia</td>
                            <td>@oElemento.Horario</td>
                            <td>@oElemento.Duracion</td>
                            <td><a class="btn btn-default" href="~/Materia/EditarMateria/@oElemento.IdMaterias">Editar</a></td>
                            <td><a class="btn btn-danger" href="~/Materia/Eliminar/@oElemento.IdMaterias">Eliminar</a></td>
                        </tr>
                    }

                </table>

    </div>

AppSchool/Views/Materia/agregarMateria.cshtml
@model AppSchool.Models.ViewModels.MateriaViewModel

@{
    ViewBag.Title = "Nuevo";
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.listaID;
}



<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("AgregarMateria", "Materia", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.DropDownList("IdCurso",items,"IdCurso", new { @class = "form-control" })
            @Html.LabelFor(d => d.Profesor)
            @Html.TextBoxFor(d => d.Profesor, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Materia)
            @Html.TextBoxFor(d => d.Materia, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Horario)
            @Html.TextBoxFor(d => d.Horario, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Duracion)
            @Html.TextBoxFor(d => d.Duracion, "", new { @class = "form-control" })
            <br />
        </div>
        <div style="margin-left:20px">
            <input value="Guardar" class="btn btn-primary" type="submit" />
        </div>
    </div>
}