AppSchool/Models/Curso.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curso()
        {
            this.Estudiantes = new HashSet<Estudiantes>();
            this.Materias = new HashSet<Materias>();
        }
    
        public int ID_curso { get; set; }
        public string Grado { get; set; }
        public string Seccion { get; set; }
        public Nullable<int> Cant_de_Estudiantes { get; set; }
        public string Profesor_encargado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estudiantes> Estudiantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materias> Materias { get; set; }
    }
}

AppSchool/Models/ViewModels/CursoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AppSchool.Models.ViewModels
{
    public class CursoViewModel
    {
        
        public int IdCurso { get; set; }
        public string Grado { get; set; }
        public string Seccion { get; set; }
        public int? CantDeEstudiantes { get; set; }
        public string ProfesorEncargado { get; set; }
    }
}

AppSchool/Controllers/CursoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AppSchool.Models;
using AppSchool.Models.ViewModels;

namespace AppSchool.Controllers
{
    public class CursoController : Controller
    {
        // GET: Curso
        public ActionResult Index()
        {
            List<ListCursoViewModel> lst;
            using (SchoolAppEntities db = new SchoolAppEntities())
            {
                lst = (from d in db.Curso
                       select new ListCursoViewModel
                       {
                           IdCurso = d.ID_curso,
                           Grado = d.Grado,
                           Seccion = d.Seccion,
                           CantDeEstudiantes = d.Cant_de_Estudiantes,
                           ProfesorEncargado = d.Profesor_encargado
                       }).ToList();
            }
            return View(lst);
        }

        public ActionResult Nuevo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(CursoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (SchoolAppEntities db = new SchoolAppEntities())
                    {
                        var oTabla = new Curso();
                        oTabla.Grado = model.Grado;
                        oTabla.Seccion = model.Seccion;
                        oTabla.Cant_de_Estudiantes = model.CantDeEstudiantes;
                        oTabla.Profesor_encargado = model.ProfesorEncargado;

                        db.Curso.Add(oTabla);
                        db.SaveChanges();
                    }
                    return Redirect("~/Curso/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult Editar(int id)
        {
            CursoViewModel model = new CursoViewModel();
            using (SchoolAppEntities db = new SchoolAppEntities())
            {
                var oTabla = db.Curso.Find(id);
                model.Grado = oTabla.Grado;
                model.Seccion = oTabla.Seccion;
                model.CantDeEstudiantes = oTabla.Cant_de_Estudiantes;
                model.ProfesorEncargado = oTabla.Profesor_encargado;
                model.IdCurso = oTabla.ID_curso;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(CursoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (SchoolAppEntities db = new SchoolAppEntities())
                    {
                        var oTabla = db.Curso.Find(model.IdCurso);
                        oTabla.Grado = model.Grado;
                        oTabla.Seccion = model.Seccion;
                        oTabla.Cant_de_Estudiantes = model.CantDeEstudiantes;
                        oTabla.Profesor_encargado = model.ProfesorEncargado;

                        db.Entry(oTabla).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    return Redirect("~/Curso/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            using (SchoolAppEntities db = new SchoolAppEntities())
            {
                var oTabla = db.Curso.Find(id);
                db.Curso.Remove(oTabla);
                db.SaveChanges();
            }
            return Redirect("~/Curso/");
        }
    } 
}

AppSchool/Views/Curso/Editar.cshtml
@model AppSchool.Models.ViewModels.CursoViewModel

@{
    ViewBag.Title = "Editar";
}



<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Editar", "Curso", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
       
            @Html.HiddenFor(d=>d.IdCurso)
            @Html.LabelFor(d => d.Grado)
            @Html.TextBoxFor(d => d.Grado, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Seccion)
            @Html.TextBoxFor(d => d.Seccion, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.CantDeEstudiantes)
            @Html.TextBoxFor(d => d.CantDeEstudiantes, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.ProfesorEncargado)
            @Html.TextBoxFor(d => d.ProfesorEncargado, "", new { @class = "form-control" })
            <br />
        </div>
        <div style="margin-left:20px">
            <input value="Guardar" class="btn btn-primary" type="submit" />
        </div>
    </div>
}

AppSchool/Views/Curso/Index.cshtml
@model List<AppSchool.Models.ViewModels.ListCursoViewModel>

    <div class="container">
        @{
            ViewBag.Title = "Curso";
        }

        <div class="page-header">
            <div class="text-center"><h1>Curso</h1></div>
        </div>
        <div class="row" style="text-align:right;padding:10px">
            <a href="~/Curso/Nuevo" class="btn btn-primary">Nuevo</a>
        </div>

                    <table class="table table-striped table-bordered text-center">
                        <tr>
                            <th>ID</th>
                            <th>Grado</th>
                            <th>Seccion</th>
                            <th>Cant. Estudiantes</th>
                            <th>Prof. Encargado</th>
                            <th>Acciones</th>
                        </tr>
                        @foreach (var oElemento in Model)
                        {
                            <tr>
                                <td>@oElemento.IdCurso</td>
                                <td>@oElemento.Grado</td>
                                <td>@oElemento.Seccion</td>
                                <td>@oElemento.CantDeEstudiantes</td>
                                <td>@oElemento.ProfesorEncargado</td>
                                <td><a class="btn btn-default" href="~/Curso/Editar/@oElemento.IdCurso">Editar</a></td>
                                <td><a class="btn btn-danger" href="~/Curso/Eliminar/@oElemento.IdCurso">Eliminar</a></td>
                            </tr>
                        }

                    </table>
             
          

    </div>

AppSchool/Views/Curso/Nuevo.cshtml
@model AppSchool.Models.ViewModels.CursoViewModel

@{
    ViewBag.Title = "Nuevo";
}



<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Nuevo","Curso",FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.LabelFor(d => d.Grado)
            @Html.TextBoxFor(d => d.Grado, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Seccion)
            @Html.TextBoxFor(d => d.Seccion, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.CantDeEstudiantes)
            @Html.TextBoxFor(d => d.CantDeEstudiantes, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.ProfesorEncargado)
            @Html.TextBoxFor(d => d.ProfesorEncargado, "", new { @class = "form-control" })
            <br />
        </div>
        <div style="margin-left:20px">
            <input value="Guardar" class="btn btn-primary" type="submit"/>
        </div>
    </div>
}