AppSchool/Models/Estudiantes.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiantes
    {
        public int ID_estudiantes { get; set; }
        public int ID_curso { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Codigo { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
    
        public virtual Curso Curso { get; set; }
    }
}

AppSchool/Models/ViewModels/EstudianteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AppSchool.Models.ViewModels
{
    public class EstudianteViewModel
    {
        public int IdEstudiantes { get; set; }
        public int IdCurso { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Sexo { get; set; }
        public int? Edad { get; set; }
        public string Codigo { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
    }
}

AppSchool/Controllers/EstudianteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AppSchool.Models;
using AppSchool.Models.ViewModels;

namespace AppSchool.Controllers
{
    public class EstudianteController : Controller
    {
        // GET: Curso
        public ActionResult Index()
        {
            List<ListEstudianteViewModel> lst;
            using (SchoolAppEntities db = new SchoolAppEntities())
            {
                lst = (from d in db.Estudiantes
                       select new ListEstudianteViewModel
                       {
                           IdEstudiantes = d.ID_estudiantes,
                           IdCurso = d.ID_curso,
                           Nombre = d.Nombre,
                           Apellido = d.Apellido,
                           Sexo = d.Sexo,
                           Edad = d.Edad,
                           Codigo = d.Codigo,
                           Telefono = d.Telefono,
                           Direccion = d.Direccion
                       }).ToList();
            }
            return View(lst);
        }

        public ActionResult agregarEstudiante()
        {
            List<ListCursoViewModel> lst;
            using (SchoolAppEntities db = new SchoolAppEntities())
            {
                lst = (from d in db.Curso
                       select new ListCursoViewModel
                       {
                           IdCurso = d.ID_curso,
                           Grado = d.Grado,
                           Seccion = d.Seccion
                       }).ToList();
            }
            List<SelectListItem> items = lst.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.Grado.ToString() + d.Seccion.ToString(),
                    Value = d.IdCurso.ToString(),
                    Selected = false
                };
            });

            ViewBag.listaID = items;
            return View();
        }

        [HttpPost]
        public ActionResult agregarEstudiante(EstudianteViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (SchoolAppEntities db = new SchoolAppEntities())
                    {
                        var oTabla = new Estudiantes();
                        oTabla.ID_curso = model.IdCurso;
                        oTabla.Nombre = model.Nombre;
                        oTabla.Apellido = model.Apellido;
                        oTabla.Sexo = model.Sexo;
                        oTabla.Edad = model.Edad;
                        oTabla.Codigo = model.Codigo;
                        oTabla.Telefono = model.Telefono;
                        oTabla.Direccion = model.Direccion;

                        db.Estudiantes.Add(oTabla);
                        db.SaveChanges();
                    }
                    return Redirect("~/Estudiante/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult EditarEstudiante(int id)
        {
            EstudianteViewModel model = new EstudianteViewModel();
            using (SchoolAppEntities db = new SchoolAppEntities())
            {
                var oTabla = db.Estudiantes.Find(id);
                model.IdCurso = oTabla.ID_curso;
                model.Nombre = oTabla.Nombre;
                model.Apellido = oTabla.Apellido;
                model.Sexo = oTabla.Sexo;
                model.Edad = oTabla.Edad;
                model.Codigo = oTabla.Codigo;
                model.Telefono = oTabla.Telefono;
                model.Direccion = oTabla.Direccion;
                model.IdEstudiantes = oTabla.ID_estudiantes;

            }
            return View(model);
        }

        [HttpPost]
        public ActionResult EditarEstudiante(EstudianteViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (SchoolAppEntities db = new SchoolAppEntities())
                    {
                        var oTabla = db.Estudiantes.Find(model.IdEstudiantes);
                        oTabla.ID_curso = model.IdCurso;
                        oTabla.Nombre = model.Nombre;
                        oTabla.Apellido = model.Apellido;
                        oTabla.Sexo = model.Sexo;
                        oTabla.Edad = model.Edad;
                        oTabla.Codigo = model.Codigo;
                        oTabla.Telefono = model.Telefono;
                        oTabla.Direccion = model.Direccion;
                   


                        db.Entry(oTabla).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    return Redirect("~/Estudiante/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            using (SchoolAppEntities db = new SchoolAppEntities())
            {
                var oTabla = db.Estudiantes.Find(id);
                db.Estudiantes.Remove(oTabla);
                db.SaveChanges();
            }
            return Redirect("~/Estudiante/");
        }
    }
}

AppSchool/Views/Estudiante/EditarEstudiante.cshtml
@model AppSchool.Models.ViewModels.EstudianteViewModel

@{
    ViewBag.Title = "Editar";
}



<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("EditarEstudiante", "Estudiante", FormMethod.Post))
{
    <div class="row">
        @Html.HiddenFor(d=>d.IdEstudiantes)
        <div class="col-md-12">
            @Html.LabelFor(d => d.IdCurso)
            @Html.TextBoxFor(d => d.IdCurso, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Nombre)
            @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Apellido)
            @Html.TextBoxFor(d => d.Apellido, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Sexo)
            @Html.TextBoxFor(d => d.Sexo, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Edad)
            @Html.TextBoxFor(d => d.Edad, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Codigo)
            @Html.TextBoxFor(d => d.Codigo, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Telefono)
            @Html.TextBoxFor(d => d.Telefono, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Direccion)
            @Html.TextBoxFor(d => d.Direccion, "", new { @class = "form-control" })
            <br />
        </div>
        <div style="margin-left:20px">
            <input value="Guardar" class="btn btn-primary" type="submit" />
        </div>
    </div>
}

AppSchool/Views/Estudiante/agregarEstudiante.cshtml
@model AppSchool.Models.ViewModels.EstudianteViewModel

@{
    ViewBag.Title = "Nuevo";
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.listaID;
}
}



<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("AgregarEstudiante", "Estudiante", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.DropDownList("IdCurso", items, "IdCurso", new { @class = "form-control" })
            @Html.LabelFor(d => d.Nombre)
            @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Apellido)
            @Html.TextBoxFor(d => d.Apellido, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Sexo)
            @Html.TextBoxFor(d => d.Sexo, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Edad)
            @Html.TextBoxFor(d => d.Edad, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Codigo)
            @Html.TextBoxFor(d => d.Codigo, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Telefono)
            @Html.TextBoxFor(d => d.Telefono, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Direccion)
            @Html.TextBoxFor(d => d.Direccion, "", new { @class = "form-control" })
            <br />
        </div>
        <div style="margin-left:20px">
            <input value="Guardar" class="btn btn-primary" type="submit" />
        </div>
    </div>
}

AppSchool/Views/Estudiante/index.cshtml
@model List<AppSchool.Models.ViewModels.ListEstudianteViewModel>

    <div class="container">
        @{
            ViewBag.Title = "Estudiante";
        }

        <div class="page-header">
            <div class="text-center"><h1>Estudiante</h1></div>
        </div>

        <div class="row" style="text-align:right;padding:10px">
            <a href="~/Estudiante/agregarEstudiante" class="btn btn-primary">Nuevo</a>
        </div>

                <table class="table table-striped table-bordered text-center">
                    <tr>
                        <th>ID</th>
                        <th>ID Curso</th>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Sexo</th>
                        <th>Edad</th>
                        <th>Codigo</th>
                        <th>Telefono</th>
                        <th>Direccion</th>
                    </tr>
                    @foreach (var oElemento in Model)
                    {
                        <tr>
                            <td>@oElemento.IdEstudiantes</td>
                            <td>@oElemento.IdCurso</td>
                            <td>@oElemento.Nombre</td>
                            <td>@oElemento.Apellido</td>
                            <td>@oElemento.Sexo</td>
                            <td>@oElemento.Edad</td>
                            <td>@oElemento.Codigo</td>
                            <td>@oElemento.Telefono</td>
                            <td>@oElemento.Direccion</td>
                            <td><a class="btn btn-default" href="~/Estudiante/EditarEstudiante/@oElemento.IdEstudiantes">Editar</a></td>
                            <td><a class="btn btn-danger" href="~/Estudiante/Eliminar/@oElemento.IdEstudiantes">Eliminar</a></td>
                        </tr>
                    }

                </table>
            </div>
    